# 主题配置，见https://blowfish.page/zh-cn/
colorScheme: Blowfish

defaultAppearance: light

autoSwitchAppearance: false

enableSearch: true

enableCodeCopy: true

disableImageOptimization: true

disableTextInHeader: false

highlightCurrentMenuArea: true

smartTOC: true

smartTOCHideUnfocusedChildren: false

env: production

header:
  layout: fixed-fill-blur

footer:
  showMenu: true
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: false
  showScrollToTop: true

homepage:
  layout: background
  showRecent: true
  showRecentItems: 3
  showMoreLink: true
  showMoreLinkDest: /blog
  cardView: false
  layoutBackgroundBlur: true

article:
  showDate: true
  showDateOnlyInArticle: false
  showDateUpdated: false
  showAuthor: true
  showAuthorBottom: true
  showHero: true
  heroStyle: basic
  layoutBackgroundBlur: true
  layoutBackgroundHeaderSpace: true
  showDraftLabel: false
  showEdit: false
  seriesOpened: true
  showHeadingAnchors: true
  showPagination: true
  showReadingTime: true
  showTableOfContents: true
  showRelatedContent: false
  relatedContentLimit: 3
  showTaxonomies: true
  showWordCount: true
  showZenMode: true
  showComments: true

list:
  layoutBackgroundHeaderSpace: true
  showSummary: true
  showCards: true
  orderByWeight: true
  groupByYear: true

robots: index,all

sitemap:
  excludedKinds:
    - taxonomy
    - term